//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SCM.WsSRIComprobanteElectronico {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SRISoap", Namespace="http://tempuri.org/")]
    public partial class SRI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RecepcionComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutorizacionComprobanteFacturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutorizacionComprobanteRetencionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SRI() {
            this.Url = global::SCM.Properties.Settings.Default.wfaFarmacia_Ney_WsSRIComprobanteElectronico_SRI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RecepcionComprobanteCompletedEventHandler RecepcionComprobanteCompleted;
        
        /// <remarks/>
        public event AutorizacionComprobanteFacturaCompletedEventHandler AutorizacionComprobanteFacturaCompleted;
        
        /// <remarks/>
        public event AutorizacionComprobanteRetencionCompletedEventHandler AutorizacionComprobanteRetencionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RecepcionComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaAutorizacionComprobante", IsNullable=true)]
        public CRespuestaAutorizacion RecepcionComprobante(string ambiente, string numeroAcceso) {
            object[] results = this.Invoke("RecepcionComprobante", new object[] {
                        ambiente,
                        numeroAcceso});
            return ((CRespuestaAutorizacion)(results[0]));
        }
        
        /// <remarks/>
        public void RecepcionComprobanteAsync(string ambiente, string numeroAcceso) {
            this.RecepcionComprobanteAsync(ambiente, numeroAcceso, null);
        }
        
        /// <remarks/>
        public void RecepcionComprobanteAsync(string ambiente, string numeroAcceso, object userState) {
            if ((this.RecepcionComprobanteOperationCompleted == null)) {
                this.RecepcionComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecepcionComprobanteOperationCompleted);
            }
            this.InvokeAsync("RecepcionComprobante", new object[] {
                        ambiente,
                        numeroAcceso}, this.RecepcionComprobanteOperationCompleted, userState);
        }
        
        private void OnRecepcionComprobanteOperationCompleted(object arg) {
            if ((this.RecepcionComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecepcionComprobanteCompleted(this, new RecepcionComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizacionComprobanteFactura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaRecepcionComprobante", IsNullable=true)]
        public CRespuestaRecepcion AutorizacionComprobanteFactura(InfoClaveAcceso InfokeyAcces, infoTributaria infoTribu, infoFactura infoFac, totalImpuesto[] tImpuesto, Pagos[] tPagos, ItemPorProducto[] tItemPorProducto, DetalleImpuestosItem[] tDetalleImpuestosItem) {
            object[] results = this.Invoke("AutorizacionComprobanteFactura", new object[] {
                        InfokeyAcces,
                        infoTribu,
                        infoFac,
                        tImpuesto,
                        tPagos,
                        tItemPorProducto,
                        tDetalleImpuestosItem});
            return ((CRespuestaRecepcion)(results[0]));
        }
        
        /// <remarks/>
        public void AutorizacionComprobanteFacturaAsync(InfoClaveAcceso InfokeyAcces, infoTributaria infoTribu, infoFactura infoFac, totalImpuesto[] tImpuesto, Pagos[] tPagos, ItemPorProducto[] tItemPorProducto, DetalleImpuestosItem[] tDetalleImpuestosItem) {
            this.AutorizacionComprobanteFacturaAsync(InfokeyAcces, infoTribu, infoFac, tImpuesto, tPagos, tItemPorProducto, tDetalleImpuestosItem, null);
        }
        
        /// <remarks/>
        public void AutorizacionComprobanteFacturaAsync(InfoClaveAcceso InfokeyAcces, infoTributaria infoTribu, infoFactura infoFac, totalImpuesto[] tImpuesto, Pagos[] tPagos, ItemPorProducto[] tItemPorProducto, DetalleImpuestosItem[] tDetalleImpuestosItem, object userState) {
            if ((this.AutorizacionComprobanteFacturaOperationCompleted == null)) {
                this.AutorizacionComprobanteFacturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutorizacionComprobanteFacturaOperationCompleted);
            }
            this.InvokeAsync("AutorizacionComprobanteFactura", new object[] {
                        InfokeyAcces,
                        infoTribu,
                        infoFac,
                        tImpuesto,
                        tPagos,
                        tItemPorProducto,
                        tDetalleImpuestosItem}, this.AutorizacionComprobanteFacturaOperationCompleted, userState);
        }
        
        private void OnAutorizacionComprobanteFacturaOperationCompleted(object arg) {
            if ((this.AutorizacionComprobanteFacturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutorizacionComprobanteFacturaCompleted(this, new AutorizacionComprobanteFacturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutorizacionComprobanteRetencion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaRecepcionComprobante", IsNullable=true)]
        public CRespuestaRecepcion AutorizacionComprobanteRetencion(InfoClaveAcceso InfokeyAcces, infoTributaria infoTribu, infoCompRetencion infoCompRetencion, DetalleImpuestosRetencion[] tDetalleImpuestosItem, DetalleInfoAdicional[] tDetalleInfoAdicional) {
            object[] results = this.Invoke("AutorizacionComprobanteRetencion", new object[] {
                        InfokeyAcces,
                        infoTribu,
                        infoCompRetencion,
                        tDetalleImpuestosItem,
                        tDetalleInfoAdicional});
            return ((CRespuestaRecepcion)(results[0]));
        }
        
        /// <remarks/>
        public void AutorizacionComprobanteRetencionAsync(InfoClaveAcceso InfokeyAcces, infoTributaria infoTribu, infoCompRetencion infoCompRetencion, DetalleImpuestosRetencion[] tDetalleImpuestosItem, DetalleInfoAdicional[] tDetalleInfoAdicional) {
            this.AutorizacionComprobanteRetencionAsync(InfokeyAcces, infoTribu, infoCompRetencion, tDetalleImpuestosItem, tDetalleInfoAdicional, null);
        }
        
        /// <remarks/>
        public void AutorizacionComprobanteRetencionAsync(InfoClaveAcceso InfokeyAcces, infoTributaria infoTribu, infoCompRetencion infoCompRetencion, DetalleImpuestosRetencion[] tDetalleImpuestosItem, DetalleInfoAdicional[] tDetalleInfoAdicional, object userState) {
            if ((this.AutorizacionComprobanteRetencionOperationCompleted == null)) {
                this.AutorizacionComprobanteRetencionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutorizacionComprobanteRetencionOperationCompleted);
            }
            this.InvokeAsync("AutorizacionComprobanteRetencion", new object[] {
                        InfokeyAcces,
                        infoTribu,
                        infoCompRetencion,
                        tDetalleImpuestosItem,
                        tDetalleInfoAdicional}, this.AutorizacionComprobanteRetencionOperationCompleted, userState);
        }
        
        private void OnAutorizacionComprobanteRetencionOperationCompleted(object arg) {
            if ((this.AutorizacionComprobanteRetencionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutorizacionComprobanteRetencionCompleted(this, new AutorizacionComprobanteRetencionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRespuestaAutorizacion {
        
        private string claveAccesoConsultadaField;
        
        private string estadoField;
        
        private int numeroComprobantesField;
        
        private Autorizacion[] autorizacionesField;
        
        private string mensajeErrorField;
        
        private bool errorField;
        
        /// <remarks/>
        public string claveAccesoConsultada {
            get {
                return this.claveAccesoConsultadaField;
            }
            set {
                this.claveAccesoConsultadaField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public int numeroComprobantes {
            get {
                return this.numeroComprobantesField;
            }
            set {
                this.numeroComprobantesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("autorizacion")]
        public Autorizacion[] autorizaciones {
            get {
                return this.autorizacionesField;
            }
            set {
                this.autorizacionesField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
            }
        }
        
        /// <remarks/>
        public bool Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Autorizacion {
        
        private string estadoField;
        
        private string numeroAutorizacionField;
        
        private string fechaAutorizacionField;
        
        private string ambienteField;
        
        private string comprobanteField;
        
        private string comprobanteRetencionField;
        
        private Mensajes[] mensajesField;
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                this.numeroAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string fechaAutorizacion {
            get {
                return this.fechaAutorizacionField;
            }
            set {
                this.fechaAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string ambiente {
            get {
                return this.ambienteField;
            }
            set {
                this.ambienteField = value;
            }
        }
        
        /// <remarks/>
        public string comprobante {
            get {
                return this.comprobanteField;
            }
            set {
                this.comprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string comprobanteRetencion {
            get {
                return this.comprobanteRetencionField;
            }
            set {
                this.comprobanteRetencionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje")]
        public Mensajes[] mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Mensajes {
        
        private string identificadorField;
        
        private string mensajeField;
        
        private string informacionAdicionalField;
        
        private string tipoField;
        
        /// <remarks/>
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string informacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalleInfoAdicional {
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalleImpuestosRetencion {
        
        private string codigoField;
        
        private string codigoRetencionField;
        
        private decimal baseImponibleField;
        
        private decimal porcentajeRetenerField;
        
        private decimal valorRetenidoField;
        
        private string codDocSustentoField;
        
        private string numDocSustentoField;
        
        private string fechaEmisionDocSustentoField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string codigoRetencion {
            get {
                return this.codigoRetencionField;
            }
            set {
                this.codigoRetencionField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImponible {
            get {
                return this.baseImponibleField;
            }
            set {
                this.baseImponibleField = value;
            }
        }
        
        /// <remarks/>
        public decimal porcentajeRetener {
            get {
                return this.porcentajeRetenerField;
            }
            set {
                this.porcentajeRetenerField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetenido {
            get {
                return this.valorRetenidoField;
            }
            set {
                this.valorRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public string codDocSustento {
            get {
                return this.codDocSustentoField;
            }
            set {
                this.codDocSustentoField = value;
            }
        }
        
        /// <remarks/>
        public string numDocSustento {
            get {
                return this.numDocSustentoField;
            }
            set {
                this.numDocSustentoField = value;
            }
        }
        
        /// <remarks/>
        public string fechaEmisionDocSustento {
            get {
                return this.fechaEmisionDocSustentoField;
            }
            set {
                this.fechaEmisionDocSustentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class infoCompRetencion {
        
        private string dirEstablecimientoField;
        
        private string obligadoContabilidadField;
        
        private string tipoIdentificacionSujetoRetenidoField;
        
        private string razonSocialSujetoRetenidoField;
        
        private string identificacionSujetoRetenidoField;
        
        private string periodoFiscalField;
        
        /// <remarks/>
        public string dirEstablecimiento {
            get {
                return this.dirEstablecimientoField;
            }
            set {
                this.dirEstablecimientoField = value;
            }
        }
        
        /// <remarks/>
        public string obligadoContabilidad {
            get {
                return this.obligadoContabilidadField;
            }
            set {
                this.obligadoContabilidadField = value;
            }
        }
        
        /// <remarks/>
        public string tipoIdentificacionSujetoRetenido {
            get {
                return this.tipoIdentificacionSujetoRetenidoField;
            }
            set {
                this.tipoIdentificacionSujetoRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public string razonSocialSujetoRetenido {
            get {
                return this.razonSocialSujetoRetenidoField;
            }
            set {
                this.razonSocialSujetoRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public string identificacionSujetoRetenido {
            get {
                return this.identificacionSujetoRetenidoField;
            }
            set {
                this.identificacionSujetoRetenidoField = value;
            }
        }
        
        /// <remarks/>
        public string periodoFiscal {
            get {
                return this.periodoFiscalField;
            }
            set {
                this.periodoFiscalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Mensaje {
        
        private string identificadorField;
        
        private string mensajeField;
        
        private string informacionAdicionalField;
        
        private string tipoField;
        
        /// <remarks/>
        public string identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string informacionAdicional {
            get {
                return this.informacionAdicionalField;
            }
            set {
                this.informacionAdicionalField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Comprobante {
        
        private string claveAccesoField;
        
        private Mensaje[] mensajesField;
        
        /// <remarks/>
        public string claveAcceso {
            get {
                return this.claveAccesoField;
            }
            set {
                this.claveAccesoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje")]
        public Mensaje[] mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRespuestaRecepcion {
        
        private string estadoField;
        
        private Comprobante[] comprobantesField;
        
        private string mensajeErrorInternoField;
        
        private bool errorInternoField;
        
        private string claveAccesoField;
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("comprobante")]
        public Comprobante[] comprobantes {
            get {
                return this.comprobantesField;
            }
            set {
                this.comprobantesField = value;
            }
        }
        
        /// <remarks/>
        public string MensajeErrorInterno {
            get {
                return this.mensajeErrorInternoField;
            }
            set {
                this.mensajeErrorInternoField = value;
            }
        }
        
        /// <remarks/>
        public bool ErrorInterno {
            get {
                return this.errorInternoField;
            }
            set {
                this.errorInternoField = value;
            }
        }
        
        /// <remarks/>
        public string ClaveAcceso {
            get {
                return this.claveAccesoField;
            }
            set {
                this.claveAccesoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DetalleImpuestosItem {
        
        private string codigoField;
        
        private string codigoPorcentajeField;
        
        private decimal tarifaField;
        
        private decimal baseImponibleField;
        
        private decimal valorField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string codigoPorcentaje {
            get {
                return this.codigoPorcentajeField;
            }
            set {
                this.codigoPorcentajeField = value;
            }
        }
        
        /// <remarks/>
        public decimal tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImponible {
            get {
                return this.baseImponibleField;
            }
            set {
                this.baseImponibleField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemPorProductoDetallesAdicionales {
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemPorProducto {
        
        private string codigoPrincipalField;
        
        private string codigoAuxiliarField;
        
        private string descripcionField;
        
        private decimal cantidadField;
        
        private decimal precioUnitarioField;
        
        private decimal descuentoField;
        
        private decimal precioTotalSinImpuestoField;
        
        private ItemPorProductoDetallesAdicionales[] detItemAdicionalField;
        
        private DetalleImpuestosItem[] detItemImpuestosField;
        
        /// <remarks/>
        public string codigoPrincipal {
            get {
                return this.codigoPrincipalField;
            }
            set {
                this.codigoPrincipalField = value;
            }
        }
        
        /// <remarks/>
        public string codigoAuxiliar {
            get {
                return this.codigoAuxiliarField;
            }
            set {
                this.codigoAuxiliarField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public decimal cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        public decimal precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public decimal descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal precioTotalSinImpuesto {
            get {
                return this.precioTotalSinImpuestoField;
            }
            set {
                this.precioTotalSinImpuestoField = value;
            }
        }
        
        /// <remarks/>
        public ItemPorProductoDetallesAdicionales[] DetItemAdicional {
            get {
                return this.detItemAdicionalField;
            }
            set {
                this.detItemAdicionalField = value;
            }
        }
        
        /// <remarks/>
        public DetalleImpuestosItem[] DetItemImpuestos {
            get {
                return this.detItemImpuestosField;
            }
            set {
                this.detItemImpuestosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pagos {
        
        private string formaPagoField;
        
        private decimal totalField;
        
        private string plazoField;
        
        private string unidadTiempoField;
        
        /// <remarks/>
        public string formaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
            }
        }
        
        /// <remarks/>
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public string plazo {
            get {
                return this.plazoField;
            }
            set {
                this.plazoField = value;
            }
        }
        
        /// <remarks/>
        public string unidadTiempo {
            get {
                return this.unidadTiempoField;
            }
            set {
                this.unidadTiempoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class totalImpuesto {
        
        private string codigoField;
        
        private string codigoPorcentajeField;
        
        private decimal baseImponibleField;
        
        private decimal descuentoAdicionalField;
        
        private decimal valorField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string codigoPorcentaje {
            get {
                return this.codigoPorcentajeField;
            }
            set {
                this.codigoPorcentajeField = value;
            }
        }
        
        /// <remarks/>
        public decimal baseImponible {
            get {
                return this.baseImponibleField;
            }
            set {
                this.baseImponibleField = value;
            }
        }
        
        /// <remarks/>
        public decimal descuentoAdicional {
            get {
                return this.descuentoAdicionalField;
            }
            set {
                this.descuentoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class infoFactura {
        
        private string dirEstablecimientoField;
        
        private string obligadoContabilidadField;
        
        private string tipoIdentificacionCompradorField;
        
        private string guiaRemisionField;
        
        private string razonSocialCompradorField;
        
        private string identificacionCompradorField;
        
        private string direccionCompradorField;
        
        private decimal totalSinImpuestosField;
        
        private decimal totalDescuentoField;
        
        private decimal propinaField;
        
        private decimal importeTotalField;
        
        private string monedaField;
        
        private decimal valorRetIvaField;
        
        private decimal valorRetRentaField;
        
        /// <remarks/>
        public string dirEstablecimiento {
            get {
                return this.dirEstablecimientoField;
            }
            set {
                this.dirEstablecimientoField = value;
            }
        }
        
        /// <remarks/>
        public string obligadoContabilidad {
            get {
                return this.obligadoContabilidadField;
            }
            set {
                this.obligadoContabilidadField = value;
            }
        }
        
        /// <remarks/>
        public string tipoIdentificacionComprador {
            get {
                return this.tipoIdentificacionCompradorField;
            }
            set {
                this.tipoIdentificacionCompradorField = value;
            }
        }
        
        /// <remarks/>
        public string guiaRemision {
            get {
                return this.guiaRemisionField;
            }
            set {
                this.guiaRemisionField = value;
            }
        }
        
        /// <remarks/>
        public string razonSocialComprador {
            get {
                return this.razonSocialCompradorField;
            }
            set {
                this.razonSocialCompradorField = value;
            }
        }
        
        /// <remarks/>
        public string identificacionComprador {
            get {
                return this.identificacionCompradorField;
            }
            set {
                this.identificacionCompradorField = value;
            }
        }
        
        /// <remarks/>
        public string direccionComprador {
            get {
                return this.direccionCompradorField;
            }
            set {
                this.direccionCompradorField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalSinImpuestos {
            get {
                return this.totalSinImpuestosField;
            }
            set {
                this.totalSinImpuestosField = value;
            }
        }
        
        /// <remarks/>
        public decimal totalDescuento {
            get {
                return this.totalDescuentoField;
            }
            set {
                this.totalDescuentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal propina {
            get {
                return this.propinaField;
            }
            set {
                this.propinaField = value;
            }
        }
        
        /// <remarks/>
        public decimal importeTotal {
            get {
                return this.importeTotalField;
            }
            set {
                this.importeTotalField = value;
            }
        }
        
        /// <remarks/>
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetIva {
            get {
                return this.valorRetIvaField;
            }
            set {
                this.valorRetIvaField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorRetRenta {
            get {
                return this.valorRetRentaField;
            }
            set {
                this.valorRetRentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class infoTributaria {
        
        private string razonSocialField;
        
        private string nombreComercialField;
        
        private string estabField;
        
        private string ptoEmiField;
        
        private string dirMatrizField;
        
        /// <remarks/>
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        public string nombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                this.nombreComercialField = value;
            }
        }
        
        /// <remarks/>
        public string estab {
            get {
                return this.estabField;
            }
            set {
                this.estabField = value;
            }
        }
        
        /// <remarks/>
        public string ptoEmi {
            get {
                return this.ptoEmiField;
            }
            set {
                this.ptoEmiField = value;
            }
        }
        
        /// <remarks/>
        public string dirMatriz {
            get {
                return this.dirMatrizField;
            }
            set {
                this.dirMatrizField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoClaveAcceso {
        
        private string fechaEmisionField;
        
        private string tipoComprobanteField;
        
        private string numRucField;
        
        private string tipoAmbienteField;
        
        private string serieField;
        
        private string numeroComprobanteField;
        
        private string codNumericoField;
        
        private string tipoEmisionField;
        
        /// <remarks/>
        public string FechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoComprobante {
            get {
                return this.tipoComprobanteField;
            }
            set {
                this.tipoComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string NumRuc {
            get {
                return this.numRucField;
            }
            set {
                this.numRucField = value;
            }
        }
        
        /// <remarks/>
        public string TipoAmbiente {
            get {
                return this.tipoAmbienteField;
            }
            set {
                this.tipoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroComprobante {
            get {
                return this.numeroComprobanteField;
            }
            set {
                this.numeroComprobanteField = value;
            }
        }
        
        /// <remarks/>
        public string CodNumerico {
            get {
                return this.codNumericoField;
            }
            set {
                this.codNumericoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoEmision {
            get {
                return this.tipoEmisionField;
            }
            set {
                this.tipoEmisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void RecepcionComprobanteCompletedEventHandler(object sender, RecepcionComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecepcionComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecepcionComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRespuestaAutorizacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRespuestaAutorizacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AutorizacionComprobanteFacturaCompletedEventHandler(object sender, AutorizacionComprobanteFacturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutorizacionComprobanteFacturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutorizacionComprobanteFacturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRespuestaRecepcion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRespuestaRecepcion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AutorizacionComprobanteRetencionCompletedEventHandler(object sender, AutorizacionComprobanteRetencionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutorizacionComprobanteRetencionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutorizacionComprobanteRetencionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CRespuestaRecepcion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRespuestaRecepcion)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591